import React, { useState } from 'react';
import { 
  BarChart3, 
  TrendingUp, 
  Calendar, 
  CheckCircle2, 
  XCircle, 
  Camera, 
  Download, 
  Printer, 
  FileText, 
  Eye, 
  X,
  Sparkles,
  ShieldCheck
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, BarChart, Bar } from 'recharts';
import { DoseLog, UserProfile, Medication } from '../types';

interface AnalyticsViewProps {
  logs: DoseLog[];
  profile: UserProfile;
  medications: Medication[];
  adherencePercent: number;
  streakDays: number;
}

export const AnalyticsView: React.FC<AnalyticsViewProps> = ({
  logs,
  profile,
  medications,
  adherencePercent,
  streakDays,
}) => {
  const [selectedPhoto, setSelectedPhoto] = useState<DoseLog | null>(null);

  // Weekly Trend Data for Recharts
  const trendData = [
    { day: 'Mon', percentage: 100 },
    { day: 'Tue', percentage: 100 },
    { day: 'Wed', percentage: 85 },
    { day: 'Thu', percentage: 100 },
    { day: 'Fri', percentage: 90 },
    { day: 'Sat', percentage: 100 },
    { day: 'Sun', percentage: 100 },
  ];

  // Time Slot Compliance Data
  const slotData = [
    { slot: 'Morning (08:00)', compliance: 98 },
    { slot: 'Midday (13:00)', compliance: 90 },
    { slot: 'Evening (20:00)', compliance: 95 },
  ];

  // Printable Provider Summary Export
  const handlePrintReport = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const printContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>DosePact Clinical Adherence Report - ${profile.name}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #1a1a1a; line-height: 1.5; }
            h1 { color: #008B8B; margin-bottom: 5px; }
            .header { border-bottom: 2px solid #008B8B; padding-bottom: 15px; margin-bottom: 20px; }
            .meta { display: flex; justify-content: space-between; margin-bottom: 20px; background: #f4f8f8; padding: 15px; border-radius: 8px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 10px; text-align: left; font-size: 13px; }
            th { background-color: #008B8B; color: white; }
            .verified { color: #008B8B; font-weight: bold; }
            .disclaimer { margin-top: 30px; font-size: 11px; color: #666; border-top: 1px solid #ccc; padding-top: 10px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>DosePact Medication Adherence Report</h1>
            <div>Generated for Healthcare Provider Review</div>
          </div>

          <div class="meta">
            <div>
              <strong>Patient Name:</strong> ${profile.name}<br>
              <strong>Age:</strong> ${profile.age} | <strong>Stomach Conditions:</strong> ${profile.stomachConditions?.join(', ') || 'N/A'}
            </div>
            <div>
              <strong>Report Date:</strong> Mon, Jul 27, 2026<br>
              <strong>7-Day Adherence:</strong> ${adherencePercent}% | <strong>Active Streak:</strong> ${streakDays} Days
            </div>
          </div>

          <h2>Current Active Medications</h2>
          <ul>
            ${medications.map((m) => `<li><strong>${m.name} (${m.dosage})</strong> - ${m.instructions} [GI Risk: ${m.giRisk}]</li>`).join('')}
          </ul>

          <h2>Dose Verification Log History</h2>
          <table>
            <thead>
              <tr>
                <th>Date & Time</th>
                <th>Schedule Slot</th>
                <th>Medications Taken</th>
                <th>Verification Status</th>
                <th>EXIF Timestamp</th>
              </tr>
            </thead>
            <tbody>
              ${logs.map((l) => `
                <tr>
                  <td>${new Date(l.takenAt).toLocaleString()}</td>
                  <td>${l.scheduleLabel}</td>
                  <td>${l.medicationsTaken.map((m) => m.name).join(', ')}</td>
                  <td class="verified">✓ Photo Verified Today</td>
                  <td>${l.exifTimestamp || 'Verified'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="disclaimer">
            This report contains digital EXIF timestamp verified medication logs generated by DosePact Adherence System.
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  return (
    <div className="space-y-8 pb-12">
      {/* Header & Export Action */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-serif italic text-[#F5F5DC]">Analytics & Provider Export</h2>
          <p className="text-xs text-[#F5F5DC]/60 mt-1">
            Comprehensive adherence charts, photo-verified dose logs, and healthcare provider reports.
          </p>
        </div>

        <button
          onClick={handlePrintReport}
          className="py-3 px-6 rounded-2xl bg-[#00CED1] text-[#1F140D] font-black text-xs uppercase tracking-wider shadow-[0_4px_20px_rgba(0,206,209,0.3)] hover:bg-[#40E0D0] transition-all flex items-center justify-center space-x-2 cursor-pointer"
        >
          <Printer className="w-4 h-4 stroke-[2.5]" />
          <span>Export Provider Summary Report</span>
        </button>
      </div>

      {/* Analytics Recharts Section */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* 7-Day Line Chart */}
        <div className="p-6 rounded-3xl bg-[#3D2B1F] border border-[#F5F5DC]/10 space-y-4 relative overflow-hidden shadow-lg">
          <div className="absolute top-0 left-0 w-1.5 h-full bg-[#00CED1]" />
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <TrendingUp className="w-5 h-5 text-[#00CED1]" />
              <h3 className="text-base font-bold text-[#F5F5DC]">7-Day Adherence Trend</h3>
            </div>
            <span className="text-xs font-bold text-[#00CED1] font-mono">{adherencePercent}% Overall</span>
          </div>

          <div className="h-56 w-full pt-2">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={trendData}>
                <XAxis dataKey="day" stroke="#F5F5DC" opacity={0.5} fontSize={11} />
                <YAxis domain={[50, 100]} stroke="#F5F5DC" opacity={0.5} fontSize={11} />
                <Tooltip
                  contentStyle={{ backgroundColor: '#1F140D', borderColor: '#00CED1', borderRadius: '12px', color: '#F5F5DC' }}
                />
                <Line
                  type="monotone"
                  dataKey="percentage"
                  stroke="#00CED1"
                  strokeWidth={3}
                  dot={{ fill: '#00CED1', r: 5 }}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Time Slot Bar Chart */}
        <div className="p-6 rounded-3xl bg-[#3D2B1F] border border-[#F5F5DC]/10 space-y-4 relative overflow-hidden shadow-lg">
          <div className="absolute top-0 left-0 w-1.5 h-full bg-[#00CED1]" />
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <BarChart3 className="w-5 h-5 text-[#00CED1]" />
              <h3 className="text-base font-bold text-[#F5F5DC]">Compliance by Time Slot</h3>
            </div>
            <span className="text-xs text-[#F5F5DC]/50">15-Min Slots</span>
          </div>

          <div className="h-56 w-full pt-2">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={slotData}>
                <XAxis dataKey="slot" stroke="#F5F5DC" opacity={0.5} fontSize={10} />
                <YAxis domain={[0, 100]} stroke="#F5F5DC" opacity={0.5} fontSize={11} />
                <Tooltip
                  contentStyle={{ backgroundColor: '#1F140D', borderColor: '#00CED1', borderRadius: '12px', color: '#F5F5DC' }}
                />
                <Bar dataKey="compliance" fill="#00CED1" radius={[8, 8, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Historical Dose Logs Table */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <Calendar className="w-5 h-5 text-[#00CED1]" />
            <h3 className="text-lg font-bold text-[#F7F4EF]">Verified Dose Log History</h3>
          </div>
          <span className="text-xs text-[#A89888]">{logs.length} Total Logs Recorded</span>
        </div>

        <div className="rounded-3xl bg-[#2A1C14] border border-[#3D2B1F] overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs text-[#D8C8B8]">
              <thead className="bg-[#1A110C] text-[#A89888] uppercase font-bold border-b border-[#3D2B1F]">
                <tr>
                  <th className="p-4">Time Taken</th>
                  <th className="p-4">Schedule Slot</th>
                  <th className="p-4">Medications</th>
                  <th className="p-4">Photo Verification</th>
                  <th className="p-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#3D2B1F]">
                {logs.map((log) => (
                  <tr key={log.id} className="hover:bg-[#3D2B1F]/40 transition-colors">
                    <td className="p-4 font-mono text-[#F7F4EF]">
                      {new Date(log.takenAt).toLocaleString([], {
                        month: 'short',
                        day: 'numeric',
                        hour: '2-digit',
                        minute: '2-digit',
                      })}
                    </td>

                    <td className="p-4 font-bold text-[#00CED1]">{log.scheduleLabel}</td>

                    <td className="p-4">
                      {log.medicationsTaken.map((m) => m.name).join(', ')}
                    </td>

                    <td className="p-4">
                      <span className="inline-flex items-center space-x-1 px-2.5 py-1 rounded-full bg-[#00CED1]/20 text-[#7FFFD4] border border-[#00CED1]/30 font-bold text-[10px]">
                        <ShieldCheck className="w-3.5 h-3.5 text-[#00CED1]" />
                        <span>Verified Photo</span>
                      </span>
                    </td>

                    <td className="p-4 text-right">
                      {log.photoUrl && (
                        <button
                          onClick={() => setSelectedPhoto(log)}
                          className="px-3 py-1.5 rounded-xl bg-[#1A110C] text-[#00CED1] hover:text-[#7FFFD4] border border-[#3D2B1F] text-xs font-semibold inline-flex items-center space-x-1"
                        >
                          <Eye className="w-3.5 h-3.5" />
                          <span>View Photo</span>
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Photo Inspection Modal */}
      <AnimatePresence>
        {selectedPhoto && (
          <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="w-full max-w-lg bg-[#2A1B13] border border-[#00CED1]/40 rounded-3xl p-6 shadow-2xl text-[#F7F4EF] space-y-4"
            >
              <div className="flex items-center justify-between pb-3 border-b border-[#3D2B1F]">
                <div>
                  <h3 className="text-base font-bold text-[#F7F4EF]">Verified Dose Photo</h3>
                  <p className="text-xs text-[#A89888]">{selectedPhoto.scheduleLabel} • {new Date(selectedPhoto.takenAt).toLocaleString()}</p>
                </div>
                <button onClick={() => setSelectedPhoto(null)} className="p-2 text-[#A89888] hover:text-[#F7F4EF]">
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Photo Image */}
              <div className="w-full aspect-video rounded-2xl overflow-hidden border border-[#00CED1]/40 bg-black">
                <img src={selectedPhoto.photoUrl} alt="Verified Dose" className="w-full h-full object-cover" />
              </div>

              <div className="p-3 rounded-2xl bg-[#1A110C] border border-[#3D2B1F] text-xs text-[#A89888] space-y-1">
                <div className="text-[#00CED1] font-bold">Verification Metadata:</div>
                <div>EXIF Timestamp: {selectedPhoto.exifTimestamp || 'Verified Today'}</div>
                <div>Verification Notes: {selectedPhoto.verificationDetails?.notes || 'Pills detected in palm.'}</div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};
